import HeroHome from "../Components/hero";
import Head from "next/head";
import { Container } from "@chakra-ui/react";
import BlogGallery from "../Components/bloggalley";
import CenterLayout from "../Components/centerlayout";

const Blog = () => {
  return (
    <main>
      <Head>
        <title>Panaverse DAO - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container padding={"0 25px"}>
        <HeroHome
          heading="The Panaverse Blog"
          desc="Get the latest insights, trends, news and updates about Web 3, Metaverse and all the upcoming future technologies"
          btntxt="See All Articles"
          btnlink="#blogs"
          gbtntxt="Web 3 Certification"
          gbtnlink="/certification"
          img = "https://i.imgur.com/AEbbttc.png"
        />
      </Container>

      <Container id="blogs">
        <BlogGallery
          card1="Advancement of Web 3 and the role of NextJS"
          card1link="/"
          card2="Advancement of Web 3 and the role of NextJS"
          card2link="/"
          card3="Advancement of Web 3 and the role of NextJS"
          card3link="/"
        />

        <BlogGallery
          card1="Advancement of Web 3 and the role of NextJS"
          card1link="/"
          card2="Advancement of Web 3 and the role of NextJS"
          card2link="/"
          card3="Advancement of Web 3 and the role of NextJS"
          card3link="/"
        />
      </Container>

      <Container>
        <CenterLayout
          heading="Become An Early Adaptor & Get Ahead"
          desc="Web3 and metaverse technologies expand the internet as we know it by introducing novel features and advancements. Become an early adaptor and grow with the technology, earning at the same time."
          bgimg="https://i.imgur.com/FC7Cmx6.jpeg"
          btntxt="Register Now"
          btnlink="https://www.piaic.org/"
        />
      </Container>
    </main>
  );
};

export default Blog;
