import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import HeroHome from '../Components/hero'
import LeftHeroText from "../Components/left-text-hero";
import Btn from '../Components/button'
import {Container} from "@chakra-ui/react"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Container>
        <HeroHome 
        heading = "A community to learn, grow and earn in Web 3"
        desc = "Panaverse DAO is a community of web 3 & metaverse developers, designers, trainers and founders that will help you to “Earn While You Learn” in Web 3"
        btntxt = "Join Panaverse"
        btnlink = "/join"
        />
        </Container>

        <LeftHeroText heading = "The Biggest Web 3 Community In Pakistan!" />
      </main>

    </>
  )
}
