import Head from "next/head";
import { Container } from "@chakra-ui/react"
import HeroHome from "../Components/hero";

export default function Home() {
  return (
    <main>
      <Head>
        <title>Panaverse DAO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        // margin={"50px 0"}
        padding="0 25px"
      >
        <HeroHome
          heading="Become A Part Of The Biggest Web3 Community In Pakistan"
          desc="Panaverse DAO is a community of web 3 & metaverse developers, designers, trainers and founders that will help you to “Earn While You Learn” in Web 3"
          btntxt="Join Panaverse"
          btnlink="https://portal.piaic.org"
          gbtntxt="Web 3 Certification"
          gbtnlink="/certification"
          img = "https://i.imgur.com/clU6JCq.png"
        />
      </Container>
    </main>
  );
}
